### ISSUE TITLE
Update Tock kernel to a more recent version

### ISSUE THREAD

**Issue by jmichelp** [google/OpenSK#148]
This involves:
- [x] Updating the submodule to a more recent commit
- [x] Update the patches
  - [x] persistent storage
  - [x] USB
  - [x] USB debugging
  - [x] additional boards 
- [x] Update the in-tree boards
- [x] Run unit tests
- [ ] Test dev kit against CTAP2 Test tool
