### ISSUE TITLE
Add vendor commands to inject crypto materials

### ISSUE THREAD

**Issue by jmichelp** [google/OpenSK#195]
Once the crypto materials are removed from the firmware (i.e. when issue #194 is fixed), we need a way to inject these values into the FOB.
The easiest way to do so is by adding vendor specific commands and provide a command line tool to run them.

For security reasons, theses commands must only be executed once and the firmware should make sure to never overwrite a value that has already been programmed.

**Comment by ia0** [comment]
Some code pointers regarding storage:
- Those [lines](https://github.com/google/OpenSK/blob/c9fc621f597e987035634aadac5c66f3e0b3fdcc/src/ctap/storage.rs#L234-L247) should be removed. Thus, the `key_material` module can be removed too.
- The vendor commands should use the `set_attestation_private_key`, `set_attestation_certificate`, and `set_aaguid` methods of the storage. If it is important that those are set at most once, I can write a PR for just that part since it's purely storage related.

**Comment by jmichelp** [comment]
AAGUID will not be set through these commands. I'd like it to still be part of the firmware at the moment.
The certification is done for a specific AAGUID and a root CA so this makes sense to have AAGUID in the firmware. Then if you inject crypto materials that are signed by the corresponding CA you run a certified key otherwise not.

**Comment by jmichelp** [comment]
List of pull requests required to achieve the goal:
- [ ] CTAP1/U2F accesses data through the store
- [ ] Vendor command is add to configure the authenticator (attestation crypto materials, JTAG lockdown)
- [ ] Capsule and syscalls are added to enable JTAG lockdown
- [ ] Configure tool to inject crypto materials in the authenticator
- [ ] Cleanup in the build script (e.g. removing openssl code/dependancy)

**Comment by ia0** [comment]
Hopefully the first point is already fixed by #112. If it's not the case, let me know. I hopefully should be able to fix it.

**Comment by kaczmarczyck** [comment]
We missed usage in [CTAP1](https://github.com/google/OpenSK/blob/master/src/ctap/ctap1.rs).

**Comment by ia0** [comment]
I see @jmichelp just sent #222 for that :-) I don't know how I missed that usage.
